# Generated by Django 4.1.13 on 2024-05-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='distric',
            new_name='district',
        ),
    ]
