# Generated by Django 4.1.13 on 2024-05-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0002_rename_distric_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_info.status'),
        ),
    ]
