# Generated by Django 4.1.13 on 2024-05-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0003_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dob',
            field=models.DateField(),
        ),
    ]
